{{- if and (eq .Values.tls "ingress") (.Values.global.enable_ironic) -}}
  {{- if eq .Values.ingress.tlsSource "self" -}}
apiVersion: cert-manager.io/v1 
kind: Certificate 
metadata:
  name: {{ include "ironic.fullname" . }}
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
spec:
  issuerRef:
    name: {{ include "ironic.fullname" . }} 
  secretName: ironic-cacert 
  ipAddresses:  
    - {{ .Values.global.provisioningIP }} 
  {{- end -}}
{{- end -}}  
