{{- if and (eq .Values.tls "ingress") (.Values.global.enable_ironic) -}}
  {{- if eq .Values.ingress.tlsSource "self" -}}
apiVersion: cert-manager.io/v1 
kind: Issuer
metadata:
  name: {{ include "ironic.fullname" . }}
  labels:
    {{- include "ironic.labels" . | nindent 4 }}
spec:
  selfSigned: {}      
  {{- end -}}
{{- end -}}  
